### ISSUE TITLE
I can't distinguish clicked works from the homepage

### ISSUE THREAD

**Issue by xiaozixun** [Catgrills/Lapis#12]
![捕获2](https://user-images.githubusercontent.com/22409452/74530330-baf28000-4f64-11ea-847c-7dbac24013ce.PNG)
![捕获](https://user-images.githubusercontent.com/22409452/74530332-bb8b1680-4f64-11ea-99b4-847a05765113.PNG)

“Pixiv : Misc Edition” and “Pixiv : Bigger Scroll Thumbnails” does not support Chinese
![捕获3](https://user-images.githubusercontent.com/22409452/74530541-42d88a00-4f65-11ea-94dd-eb655177ce4a.PNG)

**Comment by xiaozixun** [comment]
Welcome back

**Comment by Catgrills** [comment]
Hello xiao. Indeed, it has been a long time since I updated the script.

"Pixiv : Bigger Scroll Thumbnails" should work now. 
"Pixiv : Misc Edition" is now useless, I'll remove the link from the description. 

I'll try to come up with an alternative for the clicked work issue.

**Comment by xiaozixun** [comment]
> Hello xiao. Indeed, it has been a long time since I updated the script.
> 
> "Pixiv : Bigger Scroll Thumbnails" should work now.
> "Pixiv : Misc Edition" is now useless, I'll remove the link from the description.
> 
> For the clicked work issue, you can add this to the script :
> 
> .work:visited {
> border-color: #27AE60 !important;
> }
> 
> Of course, you can change the color.

I found the reason, because page elements have changed。
chinese：
![捕获](https://user-images.githubusercontent.com/22409452/74601206-974f4700-50d6-11ea-962d-040d7e6275aa.PNG)

English：
![捕获2](https://user-images.githubusercontent.com/22409452/74601216-ba79f680-50d6-11ea-894f-7051ec37b09c.PNG)

**Comment by Catgrills** [comment]
Search for "en/" in the script and remove it.
Also your header doesn't look the same as the default one I got.

**Comment by xiaozixun** [comment]
no effect, I gave up.

**Comment by Catgrills** [comment]
I posted a chinese version and I tested it, it should works now. Also I edited (again) "Bigger Scroll Thumbnails", you should update it.

I don't work for deviantArt, I don't really think the new style looks like mine !

**Comment by xiaozixun** [comment]
"Bigger Scroll Thumbnails" Chinese is still not supported。

![捕获](https://user-images.githubusercontent.com/22409452/74646599-2468cd80-51b5-11ea-8df2-74eeab888d8b.PNG)

![捕获2](https://user-images.githubusercontent.com/22409452/74646600-2599fa80-51b5-11ea-996f-e3a488a9e188.PNG)

![捕获3](https://user-images.githubusercontent.com/22409452/74646601-26cb2780-51b5-11ea-9876-7541e911fc1b.PNG)


It really doesn't look like，I made a mistake。

**Comment by Catgrills** [comment]
Sorry, my mistake, now the version is 1.0.8

**Comment by xiaozixun** [comment]
OK，everything is normal。
Thanks for your work。
