### ISSUE TITLE
for “Pixiv : Misc Edition”

### ISSUE THREAD

**Issue by xiaozixun** [Catgrills/Lapis#6]
Add an download button in the medium illustration page 
Add preview thumbnails for illustrations in manga mode
invalid
![default](https://user-images.githubusercontent.com/22409452/42032557-860731a2-7b0c-11e8-9d9f-7dcbadfc6bcd.PNG)

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=69098789

Label exceeds page

![1](https://user-images.githubusercontent.com/22409452/42032689-f15a7d10-7b0c-11e8-98bc-fa0313bc495d.PNG)

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=69392100

I use the notebook computer

**Comment by Catgrills** [comment]
Sorry for the late reply :
1) For the request, I don't think it's possible since it's a javascript dynamic layout.
2) For the issue with the tags, if you use Mozilla Firefox it should be solved.

**Comment by xiaozixun** [comment]
@Catgrills 
https://greasyfork.org/ja/scripts/5480-pixiv_expand_thumbnails


I am using chrome
