### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by Skimige** [Catgrills/Lapis#7]
## Bug 1

![image](https://user-images.githubusercontent.com/9017470/43842961-02c57660-9b59-11e8-8fe5-558f3b876382.png)

The images show directly what happened.
Also, the color of like and collect seems incorrect.

## Bug 2

![image](https://user-images.githubusercontent.com/9017470/43843133-6ca0f564-9b59-11e8-8950-f29461e182b4.png)

The "Announcement" item (with a cross on the right to close) doesn't match other item's style, and the item above it got a width which is too short, e.g. "日" goes to the second line.

**Comment by Skimige** [comment]
#### Some more info about Bug 1
It seems that Firefox can properly display the tags while Chrome cannot. This screenshot was took on Chrome.

**Comment by Catgrills** [comment]
Thanks for your report, I'll try to fix it in the next release.

**Comment by Skimige** [comment]
![snipaste_2018-08-26_15-49-25](https://user-images.githubusercontent.com/9017470/44626005-b63ca500-a947-11e8-9346-c468ab7707fe.png)

Just now I've got something else. The Like(Face) and something else have gone. [(url)](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68658202)

![snipaste_2018-08-26_15-49-56](https://user-images.githubusercontent.com/9017470/44626006-b76dd200-a947-11e8-8786-10fecb4f9d61.png)
