### ISSUE TITLE
Some elements out of place on illustration pages

### ISSUE THREAD

**Issue by flameboii** [Catgrills/Lapis#9]
On home page top bar looks fine https://i.imgur.com/Pr8dk2N.png
On illustration pages it looks like this https://i.imgur.com/NQp6nOl.png
I'm using firefox and I have installed the specified fonts.

**Comment by flameboii** [comment]
Member pages are also not affected by the style below the top bar https://i.imgur.com/T49wgO4.png

**Comment by Catgrills** [comment]
Hey flameboii, I'm aware of those "bugs", I'll post an update this weekend.

**Comment by wingfixer** [comment]
So how about that update?

**Comment by Catgrills** [comment]
Pixiv html got a bunch of random string, making it quite difficult to maintain the style, I'll search for a better alternative. If there isn't one, I guess I'll keep updating the script.

**Comment by Catgrills** [comment]
Updated the script.
